{% set name = "ploomber-scaffold" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-scaffold-{{ version }}.tar.gz
  sha256: 9d158a762a3b20e3e3c668a31b2965bafab0b2c89c3eafa1bf66209834e80f76

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - jinja2

test:
  imports:
    - ploomber_scaffold
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/ploomber
  summary: Supporting package for ploomber
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/ploomber/ploomber

extra:
  recipe-maintainers:
    - edublancas
    - RoyalTS
