{% set name = "ploomber-scaffold" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-scaffold-{{ version }}.tar.gz
  sha256: 3d66d4af4d7f91eb7eed39cec480ac4eb4832c8d2665f0c04d0e4f11985acfb3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - jinja2

test:
  imports:
    - ploomber_scaffold
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/ploomber
  summary: Supporting package for ploomber
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/ploomber/ploomber

extra:
  recipe-maintainers:
    - edublancas
    - RoyalTS
